name: Run tests and code quality checks

on: [push, pull_request]

jobs:
  build:
    name: Run tests and quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check code style with black, isort and flake8
        run: |
          black --check .
          isort --check .
          flake8
      - name: Check types with mypy
        run: mypy .
      - name: Test with pytest
        run: pytest
