name: Run tests and code quality checks

on: [push, pull_request]

jobs:
  build:
    name: Run tests and quality checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry install
      - name: Check code style with black, isort and flake8
        run: |
          poetry run black --check .
          poetry run isort --check .
          poetry run flake8
      - name: Check types with mypy
        run: poetry run mypy .
      - name: Test with pytest
        run: poetry run pytest
